ALTER TABLE public.character_sheets
  ADD COLUMN IF NOT EXISTS alcunha text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS registro_ninja text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reputacao text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reconhecimento text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS missoes_s integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missoes_a integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missoes_b integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missoes_c integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS missoes_d integer NOT NULL DEFAULT 0;